name: SSH deployment
on: push                 
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PORT: '7685'
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: "/vendor/, /storage/, /web/, /public_html/, /modules/, /config/, .htaccess, .env, .env.example"


